// <auto-generated />
namespace Warehouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductNameMaxLength100No2AndSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductNameMaxLength100No2AndSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201805241450212_Product.Name MaxLength 100 No2 And Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
